# Automatically generated by TopicTreeSpecPrinter(**kwargs).
# The kwargs were:
# - fileObj: TextIOWrapper
# - footer: '# End of topic tree definition. Note that application may l...'
# - indentStep: 4
# - treeDoc: None
# - width: 70


class ETG_read_is_flow:
    """
    UNDOCUMENTED: created without spec
    """
    
    def msgDataSpec(channel, flow):
        """
        - channel: UNDOCUMENTED
        - flow: UNDOCUMENTED
        """

class ETG_read_set_flow:
    """
    UNDOCUMENTED: created without spec
    """
    
    def msgDataSpec(channel, flow):
        """
        - channel: UNDOCUMENTED
        - flow: UNDOCUMENTED
        """

class ETG_status:
    """
    UNDOCUMENTED: created without spec
    """
    
    def msgDataSpec(text):
        """
        - text: UNDOCUMENTED
        """

class GTE_connect:
    """
    UNDOCUMENTED: created without spec
    """
    
    def msgDataSpec(port):
        """
        - port: UNDOCUMENTED
        """

class GTE_disconnect:
    """
    UNDOCUMENTED: created without spec
    """

class GTE_read_all_channels_is:
    """
    UNDOCUMENTED: created without spec
    """

class GTE_read_all_channels_set:
    """
    UNDOCUMENTED: created without spec
    """

class GTE_read_is_flow:
    """
    UNDOCUMENTED: created without spec
    """
    
    def msgDataSpec(channel):
        """
        - channel: UNDOCUMENTED
        """

class GTE_read_set_flow:
    """
    UNDOCUMENTED: created without spec
    """
    
    def msgDataSpec(channel):
        """
        - channel: UNDOCUMENTED
        """

class GTE_set_flow:
    """
    UNDOCUMENTED: created without spec
    """
    
    def msgDataSpec(channel, flow):
        """
        - channel: UNDOCUMENTED
        - flow: UNDOCUMENTED
        """


# End of topic tree definition. Note that application may load
# more than one definitions provider.
